# Generated by Django 5.2.5 on 2026-02-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='services', to='clinic.doctor', verbose_name='Врачи, оказывающие услугу'),
        ),
    ]
